### ISSUE TITLE
When I try to render a page twice, I get an error "TypeError: Cannot destructure property 'getInitialProps' of 'AppComponent' as it is undefined."

### ISSUE THREAD

**Issue by fkapsahili** [toomuchdesign/next-page-tester#155]
## 💬 Questions and Help
I am currently trying to set up some integration tests with this library, but I am still getting errors as soon as I try multiple renders in a test file.

My basic Page "404.js":
```javascript
import Link from "next/link";

export default function FourOhFour() {
  return (
    <>
      <h1>404 - Page Not Found</h1>
      <Link href="/">
        <a>Go back home</a>
      </Link>
    </>
  );
}
```

My 404.test.js file:
```javascript
import { getPage } from "next-page-tester";
import { screen } from "@testing-library/react";

describe("multiple render tests", () => {
  it("renders the 404 page", async () => {
    const { render } = await getPage({
      route: "/404",
    });
    render();

    expect(screen.getByText("404 - Page Not Found")).toBeInTheDocument();
  });

  it("renders the 404 page again", async () => {
    const { render } = await getPage({
      route: "/404",
    });
    render();

    expect(screen.getByText("404 - Page Not Found")).toBeInTheDocument();
  });
});
```

Output:
```
$ jest 404.test.js
 FAIL  test/pages/404.test.js
  multiple render tests
    ✓ renders the 404 page (66 ms)
    ✕ renders the 404 page again (3 ms)

  ● multiple render tests › renders the 404 page again

    TypeError: Cannot destructure property 'getInitialProps' of 'AppComponent' as it is undefined.

      13 | 
      14 |   it("renders the 404 page again", async () => {
    > 15 |     const { render } = await getPage({
         |                        ^
      16 |       route: "/404",
      17 |     });
      18 |     render();

      at Object.fetchAppData (node_modules/next-page-tester/dist/_app/fetchAppData.js:12:13)
      at Object.fetchRouteData (node_modules/next-page-tester/dist/fetchData/fetchRouteData.js:9:42)
      at Object.getPageInfo (node_modules/next-page-tester/dist/makePageElement.js:24:40)
      at getPage (node_modules/next-page-tester/dist/getPage.js:84:38)
      at Object.<anonymous> (test/pages/404.test.js:15:24)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        1.706 s, estimated 2 s
```

If I do the same with only one test in the describe block, I get a PASS:
```
$ jest 404.test.js
 PASS  test/pages/404.test.js
  multiple render tests
    ✓ renders the 404 page (67 ms)
```

How can I correct this error?
Grateful for any support

**Comment by fkapsahili** [comment]
I just found out that it occurs due to two CSS imports in _app.js. How can I work around this?

**Comment by Meemaw** [comment]
Maybe configuring `moduleNameMapper` in jest config would help:

```json
   "moduleNameMapper": {
      "\\.(css|less|scss)$": "identity-obj-proxy"
    },
```

**Comment by fkapsahili** [comment]
Thanks, that helped. Now I am getting the error that document is not defined when importing my styletron.ts configuration in _app.js:

```
$ jest 404.test.js
 FAIL  test/pages/404.test.js
  multiple render tests
    ✕ renders the 404 page (291 ms)

  ● multiple render tests › renders the 404 page

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/en/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: document is not defined

      12 |       route: "/404",
      13 |     });
    > 14 |     render();
         |     ^
      15 | 
      16 |     expect(screen.getByText("404 - Page Not Found")).toBeInTheDocument();
      17 |   });

      at MultiCache.onNewCache (node_modules/styletron-engine-atomic/src/client/client.js:114:30)
      at MultiCache.getCache (node_modules/styletron-engine-atomic/src/cache.js:37:12)
      at injectStylePrefixed (node_modules/styletron-engine-atomic/src/inject-style-prefixed.js:19:28)
      at StyletronClient.renderStyle (node_modules/styletron-engine-atomic/src/client/client.js:216:12)
      at driver (node_modules/styletron-standard/src/index.js:33:20)
      at Object.children (node_modules/styletron-react/src/index.js:483:36)
      at ReactDOMServerRenderer.render (node_modules/react-dom/cjs/react-dom-server.node.development.js:3972:55)
      at ReactDOMServerRenderer.read (node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
      at Object.renderToString (node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
      at node_modules/next-page-tester/dist/makeRenderMethods.js:16:75
      at Object.executeAsIfOnServerSync (node_modules/next-page-tester/dist/server.js:40:16)
      at serverRenderToString (node_modules/next-page-tester/dist/makeRenderMethods.js:16:28)
      at serverRender (node_modules/next-page-tester/dist/makeRenderMethods.js:21:26)
      at render (node_modules/next-page-tester/dist/makeRenderMethods.js:39:30)
      at Object.<anonymous> (test/pages/404.test.js:14:5)
```

styletron.ts:
```typescript
import { Client, Server } from "styletron-engine-atomic";

const getHydrateClass = () =>
  document.getElementsByClassName(
    "_styletron_hydrate_"
  ) as HTMLCollectionOf<HTMLStyleElement>;

export const styletron =
  typeof window === "undefined"
    ? new Server()
    : new Client({
        hydrate: getHydrateClass(),
      });
```

When I render the page with the render method of testing-library I pass both tests without any issues:
```
import { screen, render } from "@testing-library/react";
import App from "../../pages/404";

describe("multiple render tests", () => {
  it("renders the 404 page", async () => {
    render(<App />);

    expect(screen.getByText("404 - Page Not Found")).toBeInTheDocument();
  });

  it("renders the 404 page", async () => {
    render(<App />);

    expect(screen.getByText("404 - Page Not Found")).toBeInTheDocument();
  });
});
```

I have also tried setting the env to jsdom but without any effects. Would be grateful for more ideas as i would like to use your library

**Comment by Meemaw** [comment]
We have a test suite for `styletron-react` [here](https://github.com/toomuchdesign/next-page-tester/tree/master/src/__tests__/third-party/styletron-react). Could you check what we're doing differently as it works for us?

**Comment by fkapsahili** [comment]
Thanks, haven't even seen the third party examples. Replacing BaseProvider with ThemeProvider seems to have fixed the problem. Both tests just passed. Thanks!
```javascript       
        <StyletronProvider value={styletron}>
          <ThemeProvider theme={theme}>
            <Component {...pageProps} />
          </ThemeProvider>
        </StyletronProvider>
```
