### ISSUE TITLE
Using overridden _app & _document for MaterialUI throws "ReferenceError: document is not defined"

### ISSUE THREAD

**Issue by cneuro** [toomuchdesign/next-page-tester#195]
## 💬 Questions and Help

My `_app.js`:

```js
import React, { useEffect } from 'react';
import PropTypes from 'prop-types';
import Head from 'next/head';

import { ThemeProvider } from '@material-ui/core/styles';
import CssBaseline from '@material-ui/core/CssBaseline';

import theme from '@/components/theme';

const App = ({ Component, pageProps }) => {
  useEffect(() => {
    // Remove the server-side injected CSS (need this to stop HMR from showing React warnings)
    const jssStyles = document.querySelector('#jss-server-side');

    if (jssStyles) {
      jssStyles.parentElement.removeChild(jssStyles);
    }
  });

  return (
    <>
      <Head>
        {/* Custom header */}
      </Head>

      <ThemeProvider theme={theme}>
        <CssBaseline />

        <Component {...pageProps} />
      </ThemeProvider>
    </>
  );
};

App.propTypes = {
  Component: PropTypes.elementType.isRequired,
  pageProps: PropTypes.object.isRequired,
};

export default App;
```

My `_document.js`:

```js
import React from 'react';
import Document, { Html, Head, Main, NextScript } from 'next/document';
import { ServerStyleSheets } from '@material-ui/core/styles';

class Doc extends Document {
  render() {
    return (
      <Html lang="en">
        <Head>
          {/* Custom header */}
        </Head>

        <body>
          <Main />

          <NextScript />
        </body>
      </Html>
    );
  }

  static async getInitialProps(context) {
    // Render app and page and get the context of the page with collected side effects.
    const sheets = new ServerStyleSheets();
    const originalRenderPage = context.renderPage;

    // THIS SEEMS TO BE CAUSING ISSUES IN JEST?
    context.renderPage = () =>
      originalRenderPage({
        enhanceApp: (App) => (props) => sheets.collect(<App {...props} />),
      });

    const initialProps = await Document.getInitialProps(context);

    return {
      ...initialProps,
      // Styles fragment is rendered after the app and page rendering finish.
      styles: [...React.Children.toArray(initialProps.styles), sheets.getStyleElement()],
    };
  }
}

export default Doc;
```

NB this enables MaterialUI to play nice with the NextJS stack.

My `index.test.js`:

```js
/**
 * @jest-environment jsdom
 */

import { getPage } from 'next-page-tester';
import { screen, waitFor } from '@testing-library/react';

describe('IndexPage', () => {
  it('shows index page', async () => {
    const { render } = await getPage({ route: '/', useDocument: true });

    render();

    // Some other stuff ...
  });
});
```

When running the test:

```bash
$ jest
 FAIL  test/index.test.js (27.528 s)
  IndexPage
    ✕ shows index page (13297 ms)

  ● IndexPage › shows index page

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/en/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: document is not defined

      55 |
      56 |     context.renderPage = () =>
    > 57 |       originalRenderPage({
         |       ^
      58 |         enhanceApp: (App) => (props) => sheets.collect(<App {...props} />),
      59 |       });
      60 |
```

The error is the same whether or not I include the `@jest-environment` docblock in the test file.

If I omit `useDocument: true` from the `getPage()` options I get the failure a bit later, but with the same error:

```bash
$ jest
 FAIL  test/index.test.js (19.88 s)
  IndexPage
    ✕ shows index page (9129 ms)

  ● IndexPage › shows index page

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/en/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: document is not defined

      10 |     const { render } = await getPage({ route: '/' });
      11 |
    > 12 |     render();
         |     ^
      13 |
      14 |     expect(screen.getByRole('progressbar')).toBeInTheDocument();
      15 |
```

NB I've patched jest according to https://github.com/toomuchdesign/next-page-tester#optional-patch-jest. I'm running jest v26.6.3 .

I'm probably missing something obvious. Anyone have an idea?

Thanks!

**Comment by Meemaw** [comment]
Hey @cneuro 👋 We need a reproducible example (link to a GH repo) in order to investigate this.

**Comment by domhede** [comment]
Hello 👋 
I too am getting a similar error.  
This is a demo repo: https://github.com/domhede/next-cypress-jest-apollo-example

**Comment by domhede** [comment]
Hey I actually managed to get it working in my demo repo.  I found the fix was to wrap my assertions in `waitFor` and use `queryByText`.  see: https://github.com/domhede/next-page-tester-demo/commit/49f0c3c83578a14ee31e1560f2b5c3e38114b7d2

**Comment by ThePicoNerd** [comment]
I had the same problem (using just a custom document), and managed to fix it by upgrading react and react-dom to version 17.

**Comment by cullylarson** [comment]
I'm getting the same error. Though I'm getting it at the `render` call, so the `waitFor` solution that @domhede posted doesn't work/apply. My test looks like:

```js
import {getPage} from 'next-page-tester'
import {render, screen} from '@testing-library/react'

jest.mock('react', () => ({
    ...jest.requireActual('react'),
    useLayoutEffect: jest.requireActual('react').useEffect,
}));

test('Renders without crashing.', async () => {
    const {render} = await getPage({
        route: '/',
    })

    render() // <--- this is where the error path begins

    expect(screen.getByRole('heading', {name: 'This is not the heading'})).toBeInTheDocument()
})
```

This is the error I'm getting:

```
 FAIL  tests/pages/index.test.js
  ● Renders without crashing.

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/en/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.

    ReferenceError: document is not defined

      12 |     })
      13 |
    > 14 |     render()
         |     ^
      15 |
      16 |     expect(screen.getByRole('heading', {name: 'This is not the heading'})).toBeInTheDocument()
      17 | })

      at StyleSheetRegistry.selectFromServer (node_modules/styled-jsx/dist/stylesheet-registry.js:235:47)
      at StyleSheetRegistry.add (node_modules/styled-jsx/dist/stylesheet-registry.js:61:31)
      at JSXStyle.render (node_modules/styled-jsx/dist/style.js:58:26)
      at processChild (node_modules/react-dom/cjs/react-dom-server.node.development.js:3450:18)
      at resolve (node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
      at ReactDOMServerRenderer.render (node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
      at ReactDOMServerRenderer.read (node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
      at Object.renderToString (node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
      at node_modules/next-page-tester/dist/makeRenderMethods.js:16:75
      at Object.executeAsIfOnServerSync (node_modules/next-page-tester/dist/server.js:39:16)
      at serverRenderToString (node_modules/next-page-tester/dist/makeRenderMethods.js:16:28)
      at serverRender (node_modules/next-page-tester/dist/makeRenderMethods.js:21:26)
      at render (node_modules/next-page-tester/dist/makeRenderMethods.js:39:30)
      at Object.<anonymous> (tests/pages/index.test.js:14:5)
```

It looks like an issue with styled-jsx (at least, that's where the reference to `document` is made).

Here's the versions of pertinent packages I'm using:

```
    "@testing-library/dom": "7.30.3",
    "@testing-library/jest-dom": "5.11.10",
    "@testing-library/react": "11.2.6",
    "jest": "26.6.3",
    "next": "10.1.3",
    "next-page-tester": "0.24.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
```

**Comment by Abd-ksr** [comment]
I am also getting same error. Is there any workaround?

```
"next": "10.0.5",
"react": "17.0.1",
"react-dom": "17.0.1",
"jest": "26.6.3",
"@testing-library/react": "11.2.6",
"next-page-tester": "0.22.0"
```

**Comment by toomuchdesign** [comment]
Hi all,
we'd need a minimal runnable repro of the issue.
Is https://github.com/domhede/next-page-tester-demo still relevant?

**Comment by domhede** [comment]
@toomuchdesign It's working in my demo repo now: https://github.com/domhede/next-page-tester-demo.

**Comment by jyk2000** [comment]
I'm having same issue as well. 
`"devDependencies": {
    "@testing-library/dom": "^7.30.3",
    "@testing-library/jest-dom": "^5.11.10",
    "@testing-library/react": "^11.2.6",
    "babel-eslint": "^10.0.3",
    "babel-jest": "^26.6.3",
    "eslint": "^6.7.2",
    "eslint-config-prettier": "^6.7.0",
    "eslint-loader": "^3.0.3",
    "eslint-plugin-react": "^7.17.0",
    "eslint-plugin-react-hooks": "^2.3.0",
    "jest": "^26.6.3",
    "next-page-tester": "^0.24.2"
  },
  "jest": {
    "testPathIgnorePatterns": [
      "<rootDir>/.next/",
      "<rootDir>/node_modules/"
    ],
    "transform": {
      "^.+\\.(js|jsx|ts|tsx)$": "<rootDir>/node_modules/babel-jest"
    },
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__mocks__/fileMock.js",
      "\\.(css|less)$": "<rootDir>/__mocks__/styleMock.js"
    },
    "verbose": true,
    "testEnvironment": "jsdom"
  }`

**Comment by jyk2000** [comment]
For anyone having the error coming from styled-jsx selectFromServer function, I fixed the issue by changing .babelrc 
I still have another issue to fix but at least the "document not defined" part, I passed.  
```
{
  "presets": ["next/babel"],
  // this is what you're adding:
  "env": {
    "test": {
      "presets": [
        [
          "next/babel",
          {
            "styled-jsx": {
              "babel-test": true
            }
          }
        ]
      ]
    }
  }
}
```
