### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by utiq** [toomuchdesign/next-page-tester#200]
I didn't patch nextjs yet, I wanted to know if it is necessary, I got this error
```
 FAIL  pages/__test__/index.test.js
  ● Test suite failed to run

    Cannot find module 'next/dist/next-server/server/config-utils' from 'node_modules/next-page-tester/dist/nextConfig.js'

    Require stack:
      node_modules/next-page-tester/dist/nextConfig.js
      node_modules/next-page-tester/dist/utils.js
      node_modules/next-page-tester/dist/getPageObject/makeRouteInfo.js
      node_modules/next-page-tester/dist/getPageObject/index.js
      node_modules/next-page-tester/dist/page/getPageInfo.js
      node_modules/next-page-tester/dist/page/index.js
      node_modules/next-page-tester/dist/getPage.js
      node_modules/next-page-tester/dist/pure.js
      node_modules/next-page-tester/dist/index.js
      pages/__test__/index.test.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/next-page-tester/dist/nextConfig.js:19:21)
```

**Comment by toomuchdesign** [comment]
Probably using the wrong `next-page-tester` version. See [here](https://github.com/toomuchdesign/next-page-tester#nextjs-versions-support).
