### ISSUE TITLE
fast-glob does not support backslash after 3.0 and it causes windows environment fail to find route. 

### ISSUE THREAD

**Issue by jyk2000** [toomuchdesign/next-page-tester#206]
## 🐛 Bug Report

fast-glob used inside getPagePath.js is causing issue on windows due to backslash. 
fast-glob after 3.0 does not auto replace backslash to forward ones anymore. 
 - fast-glob 3.0 release note : https://github.com/mrmlnc/fast-glob/releases/tag/3.0.0

This caused my test on windows to output below error 
- [next page tester] No matching page found for given route

## Reproduction

My test code 
```
describe('Page Rendering Test', () => {
  it('renders home page', async() => {
    const { render } = await getPage({
      route: '/'
    })

    render()
    expect(screen.getByText('Latest Oncology News')).toBeInTheDocument()
  })
})
```

Test output 
```
Page Rendering Test
    × renders home page (2616 ms)

  ● Page Rendering Test › renders home page

    [next page tester] No matching page found for given route

      17 | describe('Page Rendering Test', () => {
      18 |   it('renders home page', async() => {
    > 19 |     const { render } = await getPage({
         |                        ^
      20 |       route: '/'
      21 |     })
      22 | 

      at Object.getPageObject [as default] (node_modules/next-page-tester/dist/getPageObject.js:23:11)
      at makePage (node_modules/next-page-tester/dist/getPage.js:42:28)
      at getPage (node_modules/next-page-tester/dist/getPage.js:51:41)
```

pagesDirectory props inside getPagePaths.js becomes below on windows 
```
C:\Users\jyk20\react\www.onclive.com/pages
```

I'm using v0.7.0 to match next version I'm using - v9.5.4
```
"devDependencies": {
    "@testing-library/dom": "^7.30.3",
    "@testing-library/jest-dom": "^5.11.10",
    "@testing-library/react": "^11.2.6",
    "babel-eslint": "^10.0.3",
    "babel-jest": "^26.6.3",
    "eslint": "^6.7.2",
    "eslint-config-prettier": "^6.7.0",
    "eslint-loader": "^3.0.3",
    "eslint-plugin-react": "^7.17.0",
    "eslint-plugin-react-hooks": "^2.3.0",
    "jest": "^26.6.3",
    "next-page-tester": "0.7.0"
  },
```

## Expected behavior

getPagePath needs to replace backslash to forward slash before calling fast-glob. 

## Jest patch

Have you patched Jest as [described here](https://github.com/toomuchdesign/next-page-tester#optional-patch-jest)?

- [ ] yes
- [x] no

## Run `npx envinfo --preset jest`

Paste the results here:

```
npx: installed 1 in 0.862s

  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900KF @ 3.50GHz
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    jest: ^26.6.3 => 26.6.3
```

**Comment by jyk2000** [comment]
I found upgrading nextjs to 10.0.3 and next-page-tester to ^0.24.2 fixed the issue. 
But now I'm facing another issue. 
```
  ● Page Rendering Test › renders home page

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/en/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.

    ReferenceError: document is not defined

      27 |     })
      28 | 
    > 29 |     render()
         |     ^
      30 |     expect(screen.getByText('Latest Oncology News')).toBeInTheDocument()
      31 |   })
      32 | })

      at StyleSheetRegistry.selectFromServer (node_modules/styled-jsx/dist/stylesheet-registry.js:235:47)
      at StyleSheetRegistry.add (node_modules/styled-jsx/dist/stylesheet-registry.js:61:31)
      at JSXStyle.render (node_modules/styled-jsx/dist/style.js:58:26)
      at processChild (node_modules/react-dom/cjs/react-dom-server.node.development.js:3134:18)
      at resolve (node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
      at ReactDOMServerRenderer.render (node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
      at ReactDOMServerRenderer.read (node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
      at Object.renderToString (node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
      at node_modules/next-page-tester/dist/makeRenderMethods.js:16:75
      at Object.executeAsIfOnServerSync (node_modules/next-page-tester/dist/server.js:39:16)
      at serverRenderToString (node_modules/next-page-tester/dist/makeRenderMethods.js:16:28)
      at serverRender (node_modules/next-page-tester/dist/makeRenderMethods.js:21:26)
      at render (node_modules/next-page-tester/dist/makeRenderMethods.js:39:30)
      at Object.<anonymous> (__tests__/index.test.js:29:5)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        6.161 s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by jyk2000** [comment]
Test environment is jsdom. 
And selectFromServer() in stylesheet-registry.js is using document.querySelector() and the "document" is undefined. 
I'm not sure how to fix this.

**Comment by jyk2000** [comment]
Found dup issue. closing.
