### ISSUE TITLE
"Invalid hook call" from _app.js

### ISSUE THREAD

**Issue by jakeorr** [toomuchdesign/next-page-tester#231]
Hello,

I'm working on getting tests setup for my Next.js 10 app and using this package (which seems really useful, thanks for all your work!). Here is the test that's failing:

```js
import { getPage } from 'next-page-tester';
import { screen } from '@testing-library/react';

test('renders the heading', async () => {
  const { render } = await getPage({
    route: '/brands',
  });

  render();

  expect(screen.getByRole('heading', { name: 'Brands' })).toBeInTheDocument();
});
```

The error is happening in `_app.js`:

```
 FAIL  __tests__/pages/brands/index.test.js (5.387 s)
  ✕ renders the heading (829 ms)

  ● renders the heading

    Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
    1. You might have mismatching versions of React and the renderer (such as React DOM)
    2. You might be breaking the Rules of Hooks
    3. You might have more than one copy of React in the same app
    See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

      14 |
      15 | function MyApp({ Component, pageProps }) {
    > 16 |   const queryClientRef = useRef();
         |                          ^
      17 |
      18 |   if (!queryClientRef.current) {
      19 |     queryClientRef.current = new QueryClient();

      at resolveDispatcher (node_modules/react/cjs/react.development.js:1476:13)
      at useRef (node_modules/react/cjs/react.development.js:1515:20)
      at MyApp (pages/_app.js:16:26)
      at processChild (../node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
      at resolve (../node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
      at ReactDOMServerRenderer.render (../node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
      at ReactDOMServerRenderer.read (../node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
      at Object.renderToString (../node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
      at ../node_modules/next-page-tester/dist/makeRenderMethods.js:16:75
      at Object.executeAsIfOnServerSync (../node_modules/next-page-tester/dist/server.js:39:16)
      at serverRenderToString (../node_modules/next-page-tester/dist/makeRenderMethods.js:16:28)
      at serverRender (../node_modules/next-page-tester/dist/makeRenderMethods.js:21:26)
      at render (../node_modules/next-page-tester/dist/makeRenderMethods.js:39:30)
      at Object.<anonymous> (__tests__/pages/brands/index.test.js:16:3)
```

This is `_app.js`:

```js
import { useRef } from 'react';
import { QueryClient, QueryClientProvider } from 'react-query';

export default function MyApp({ Component, pageProps }) {
  const queryClientRef = useRef();

  if (!queryClientRef.current) {
    queryClientRef.current = new QueryClient();
  }

  ...
}
```

I'm using a number of providers, but I left them out for now. I can share more if that would be helpful.

"next": "10.2.2"
"jest": "^27.0.1"
"react": "17.0.2"

Do you have any ideas?

**Comment by toomuchdesign** [comment]
Hi @jakeorr,
would you mind [providing a minimal repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)?

**Comment by jakeorr** [comment]
Thanks for the response, @toomuchdesign. I will get that repro setup for you in the next few days.

**Comment by jakeorr** [comment]
Well, doing the repro was a great idea; I've resolved this issue. Looks like it was an issue with how my docker container was setup. Closing the issue. Thanks!
