### ISSUE TITLE
 SyntaxError: Invalid regular expression: Invalid capture group name

### ISSUE THREAD

**Issue by feargalWag** [toomuchdesign/next-page-tester#258]
## 🐛 Bug Report

After writing the sample test right from the docs with a path to a page in our local app it's not querying the regex of all of our pages, just a small subset it seems.

## Reproduction
```
    SyntaxError: Invalid regular expression: /^/ask-an-expert/past-questions/(?<ownerId>[^/?]*)/questions/(?<question-id>[^/?]*)$/: Invalid capture group name
        at new RegExp (<anonymous>)

      79 |
      80 |   it('renders daily wag page', async() => {
    > 81 |     const render = await getPage({
         |                    ^
      82 |       route: '/daily/a-dog-can-be-good-for-your-health',
      83 |     })
      84 |   });

      at Object.pagePathToRouteRegex (node_modules/next-page-tester/dist/getPageObject/pagePathParser.js:50:12)
      at Object.getRouteInfo [as default] (node_modules/next-page-tester/dist/getPageObject/getRouteInfo.js:15:48)
      at Object.getPageObject (node_modules/next-page-tester/dist/getPageObject/getPageObject.js:13:23)
      at Object.getPageInfo (node_modules/next-page-tester/dist/page/getPageInfo.js:13:24)
      at getPage (node_modules/next-page-tester/dist/getPage.js:66:38)
      at Object.<anonymous> (src/containers/DailyWagArticlePageContainer/tests/daily-wag-article-slug.test.tsx:81:20)

```

```
beforeEach(() => {
  // Mocks next/router library
  useRouter.mockImplementationOnce(() => ({
    asPath: '/',
    pathname: '/daily',
  }));
  // setup();
  // heroCta = screen.getByTestId('daily-wag-hero-cta');
});

describe('DailyWagArticle', () => {
  // it('should render hero cta', () => {
  //   expect(heroCta).toBeTruthy();
  // });

  it('renders daily wag page', async() => {
    const render = await getPage({
      route: '/daily/a-dog-can-be-good-for-your-health',
    })
  });

  // it('should render the correct utm paremeters on the hero cta', () => {
  //   expect(heroCta.href).toEqual(textExpectedCtaUrl);
  // });
});

```
```

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        5.924s, estimated 8s
```
Please provide a link to a minimal GitHub repo reproducing the issue _(we won't be able to provide support otherwise)_.
It's proprietary software so I can't 
## Expected behavior
To be able to query the whole regex of the pages we have rather than this subset.
## Jest patch

Have you patched Jest as [described here](https://github.com/toomuchdesign/next-page-tester#optional-patch-jest)?

- [ ] yes
- [x] no

## Run `npx envinfo --preset jest`

Paste the results here:

```bash
  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v14.16.1/bin/npm
  npmPackages:
    jest: ^27.2.0 => 27.2.0

"next": "^11.1.2",
"next-page-tester": "^0.28.0",


```

**Comment by toomuchdesign** [comment]
Hi @feargalWag,
in order to provide support [a repro or a PR with relevant failing test is needed](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff). Provided info is not sufficient.
