### ISSUE TITLE
act() warnings when just rendering a page

### ISSUE THREAD

**Issue by thepuzzlemaster** [toomuchdesign/next-page-tester#288]
## 🐛 Bug Report

I am trying to get next-page-tester up and running and have run into an issue where trying to render a page results in the following error messaging.
```bash
Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "Warning: An update to Root inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at Root (/Projects/radious/src/features/Root/Root.tsx:67:48)
        at MyApp (/Projects/radious/pages/_app.tsx:37:3)
        at Provider (/Projects/radious/node_modules/react-redux/lib/components/Provider.js:21:20)
        at Wrapper (/Projects/radious/node_modules/next-redux-wrapper/src/index.tsx:150:17)
        at RouterProvider (/Projects/radious/node_modules/next-page-tester/dist/router/RouterProvider.js:31:27)".

      65 |     (referralId: string) => {
      66 |       dispatch(setReferralId(referralId))
    > 67 |       writeStorage(LocalStorage.ReferralId, referralId)
             |                                                                         ^
      68 |     },
      69 |     [dispatch]
      70 |   )
```
The thing is, I don't even understand why this code would be running, as it only should get triggered if the URL has a specific query param inside it, which it shouldn't for this test.

This is my entire test
```
describe('BookingPreviewPage', () => {
  it('renders BookingPreview page', async () => {
    const { render } = await getPage({
      route: RoutesMap.BookingPreview.route,
    })

    render()
  })
})

```
## Reproduction

Unfortunately, I haven't been able to come up with a minimal repro, and can't post my full source code :/
I'm hoping maybe I'm just missing something that might be obvious.

I will add that the page I am trying to load, requires authentication. which I've mocked the `getSession()` call using msw, which seems to be working correctly. But perhaps there is some interplay between the api responses there and in getServerSideProps, which are causing issues? The way I have it set up, my app kind of has 2 getServerSideProps calls. Could that be causing the issue here?

## Expected behavior

No act() warnings when just rendering a page.

## Jest patch

Have you patched Jest as [described here](https://github.com/toomuchdesign/next-page-tester#optional-patch-jest)?

- [ ] yes
- [x] no
I am using jest v27.3.1, so my understanding is that patching is only for v26.

## Run `npx envinfo --preset jest`
```bash
System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 17.0.1 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.0 - /opt/homebrew/bin/npm
  npmPackages:
    jest: ^27.3.1 => 27.3.1
```

**Comment by thepuzzlemaster** [comment]
Well this is embarrassing. 

I'm not 100% sure what was the cause of this error, but one major problem with my test was that I was forgetting an id in the route.

I had my route in the test as: `route: RoutesMap.BookingPreview.route`

However, what I needed it to be was:
```bash
route: `${RoutesMap.BookingPreview.route}/123456,`
```

I'm still having some other issues, but all the `act()` warnings have gone away.

Sorry for the noise, but maybe this will be useful for someone else in the future.
